/*
* generated by Xtext
*/
package at.ac.tuwien.big.forms.form.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class FormGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class FormModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FormModel");
		private final Assignment cFormsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cFormsFormParserRuleCall_0 = (RuleCall)cFormsAssignment.eContents().get(0);
		
		//// implement your grammar here, starting with the root element: FormModel
		//FormModel:
		//	forms+=Form*;
		public ParserRule getRule() { return rule; }

		//forms+=Form*
		public Assignment getFormsAssignment() { return cFormsAssignment; }

		//Form
		public RuleCall getFormsFormParserRuleCall_0() { return cFormsFormParserRuleCall_0; }
	}

	public class FormElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Form");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cWelcomeFormAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cWelcomeFormWelcomeKeyword_0_0 = (Keyword)cWelcomeFormAssignment_0.eContents().get(0);
		private final Keyword cFormKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Assignment cTitleAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTitleSTRINGTerminalRuleCall_3_0 = (RuleCall)cTitleAssignment_3.eContents().get(0);
		private final Keyword cHandlesKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cEntityAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cEntityEntityCrossReference_5_0 = (CrossReference)cEntityAssignment_5.eContents().get(0);
		private final RuleCall cEntityEntityIDTerminalRuleCall_5_0_1 = (RuleCall)cEntityEntityCrossReference_5_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cPagesAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cPagesPageParserRuleCall_7_0 = (RuleCall)cPagesAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Form:
		//	welcomeForm?="welcome"? "form" name=ID title=STRING "handles" entity=[Entity] "{" pages+=Page* "}";
		public ParserRule getRule() { return rule; }

		//welcomeForm?="welcome"? "form" name=ID title=STRING "handles" entity=[Entity] "{" pages+=Page* "}"
		public Group getGroup() { return cGroup; }

		//welcomeForm?="welcome"?
		public Assignment getWelcomeFormAssignment_0() { return cWelcomeFormAssignment_0; }

		//"welcome"
		public Keyword getWelcomeFormWelcomeKeyword_0_0() { return cWelcomeFormWelcomeKeyword_0_0; }

		//"form"
		public Keyword getFormKeyword_1() { return cFormKeyword_1; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//title=STRING
		public Assignment getTitleAssignment_3() { return cTitleAssignment_3; }

		//STRING
		public RuleCall getTitleSTRINGTerminalRuleCall_3_0() { return cTitleSTRINGTerminalRuleCall_3_0; }

		//"handles"
		public Keyword getHandlesKeyword_4() { return cHandlesKeyword_4; }

		//entity=[Entity]
		public Assignment getEntityAssignment_5() { return cEntityAssignment_5; }

		//[Entity]
		public CrossReference getEntityEntityCrossReference_5_0() { return cEntityEntityCrossReference_5_0; }

		//ID
		public RuleCall getEntityEntityIDTerminalRuleCall_5_0_1() { return cEntityEntityIDTerminalRuleCall_5_0_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_6() { return cLeftCurlyBracketKeyword_6; }

		//pages+=Page*
		public Assignment getPagesAssignment_7() { return cPagesAssignment_7; }

		//Page
		public RuleCall getPagesPageParserRuleCall_7_0() { return cPagesPageParserRuleCall_7_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}

	public class PageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Page");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPageKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTitleAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTitleSTRINGTerminalRuleCall_1_0 = (RuleCall)cTitleAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Assignment cPageElementsAssignment_3_0 = (Assignment)cGroup_3.eContents().get(0);
		private final RuleCall cPageElementsPageElementParserRuleCall_3_0_0 = (RuleCall)cPageElementsAssignment_3_0.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cGroup_3.eContents().get(1);
		private final Keyword cCommaKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final Assignment cPageElementsAssignment_3_1_1 = (Assignment)cGroup_3_1.eContents().get(1);
		private final RuleCall cPageElementsPageElementParserRuleCall_3_1_1_0 = (RuleCall)cPageElementsAssignment_3_1_1.eContents().get(0);
		private final Assignment cConditionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cConditionConditionParserRuleCall_4_0 = (RuleCall)cConditionAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Page:
		//	"page" title=STRING "{" (pageElements+=PageElement ("," pageElements+=PageElement)*)? condition=Condition? "}";
		public ParserRule getRule() { return rule; }

		//"page" title=STRING "{" (pageElements+=PageElement ("," pageElements+=PageElement)*)? condition=Condition? "}"
		public Group getGroup() { return cGroup; }

		//"page"
		public Keyword getPageKeyword_0() { return cPageKeyword_0; }

		//title=STRING
		public Assignment getTitleAssignment_1() { return cTitleAssignment_1; }

		//STRING
		public RuleCall getTitleSTRINGTerminalRuleCall_1_0() { return cTitleSTRINGTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//(pageElements+=PageElement ("," pageElements+=PageElement)*)?
		public Group getGroup_3() { return cGroup_3; }

		//pageElements+=PageElement
		public Assignment getPageElementsAssignment_3_0() { return cPageElementsAssignment_3_0; }

		//PageElement
		public RuleCall getPageElementsPageElementParserRuleCall_3_0_0() { return cPageElementsPageElementParserRuleCall_3_0_0; }

		//("," pageElements+=PageElement)*
		public Group getGroup_3_1() { return cGroup_3_1; }

		//","
		public Keyword getCommaKeyword_3_1_0() { return cCommaKeyword_3_1_0; }

		//pageElements+=PageElement
		public Assignment getPageElementsAssignment_3_1_1() { return cPageElementsAssignment_3_1_1; }

		//PageElement
		public RuleCall getPageElementsPageElementParserRuleCall_3_1_1_0() { return cPageElementsPageElementParserRuleCall_3_1_1_0; }

		//condition=Condition?
		public Assignment getConditionAssignment_4() { return cConditionAssignment_4; }

		//Condition
		public RuleCall getConditionConditionParserRuleCall_4_0() { return cConditionConditionParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class PageElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PageElement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final RuleCall cRelationshipPageElementParserRuleCall_0_0 = (RuleCall)cAlternatives_0.eContents().get(0);
		private final RuleCall cAttributePageElementParserRuleCall_0_1 = (RuleCall)cAlternatives_0.eContents().get(1);
		private final Assignment cConditionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cConditionConditionParserRuleCall_1_0 = (RuleCall)cConditionAssignment_1.eContents().get(0);
		
		//PageElement:
		//	(RelationshipPageElement | AttributePageElement) condition=Condition?;
		public ParserRule getRule() { return rule; }

		//(RelationshipPageElement | AttributePageElement) condition=Condition?
		public Group getGroup() { return cGroup; }

		//RelationshipPageElement | AttributePageElement
		public Alternatives getAlternatives_0() { return cAlternatives_0; }

		//RelationshipPageElement
		public RuleCall getRelationshipPageElementParserRuleCall_0_0() { return cRelationshipPageElementParserRuleCall_0_0; }

		//AttributePageElement
		public RuleCall getAttributePageElementParserRuleCall_0_1() { return cAttributePageElementParserRuleCall_0_1; }

		//condition=Condition?
		public Assignment getConditionAssignment_1() { return cConditionAssignment_1; }

		//Condition
		public RuleCall getConditionConditionParserRuleCall_1_0() { return cConditionConditionParserRuleCall_1_0; }
	}

	public class RelationshipPageElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RelationshipPageElement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final RuleCall cListParserRuleCall_0_0 = (RuleCall)cAlternatives_0.eContents().get(0);
		private final RuleCall cTableParserRuleCall_0_1 = (RuleCall)cAlternatives_0.eContents().get(1);
		private final Keyword cEditsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cEditingFormAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cEditingFormFormCrossReference_2_0 = (CrossReference)cEditingFormAssignment_2.eContents().get(0);
		private final RuleCall cEditingFormFormIDTerminalRuleCall_2_0_1 = (RuleCall)cEditingFormFormCrossReference_2_0.eContents().get(1);
		
		//RelationshipPageElement:
		//	(List | Table) "edits" editingForm=[Form];
		public ParserRule getRule() { return rule; }

		//(List | Table) "edits" editingForm=[Form]
		public Group getGroup() { return cGroup; }

		//List | Table
		public Alternatives getAlternatives_0() { return cAlternatives_0; }

		//List
		public RuleCall getListParserRuleCall_0_0() { return cListParserRuleCall_0_0; }

		//Table
		public RuleCall getTableParserRuleCall_0_1() { return cTableParserRuleCall_0_1; }

		//"edits"
		public Keyword getEditsKeyword_1() { return cEditsKeyword_1; }

		//editingForm=[Form]
		public Assignment getEditingFormAssignment_2() { return cEditingFormAssignment_2; }

		//[Form]
		public CrossReference getEditingFormFormCrossReference_2_0() { return cEditingFormFormCrossReference_2_0; }

		//ID
		public RuleCall getEditingFormFormIDTerminalRuleCall_2_0_1() { return cEditingFormFormIDTerminalRuleCall_2_0_1; }
	}

	public class TableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Table");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTableKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cElementIDAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cElementIDIDTerminalRuleCall_1_0 = (RuleCall)cElementIDAssignment_1.eContents().get(0);
		private final Assignment cLabelAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLabelSTRINGTerminalRuleCall_2_0 = (RuleCall)cLabelAssignment_2.eContents().get(0);
		private final Keyword cHandlesKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cRelationshipAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cRelationshipRelationshipCrossReference_4_0 = (CrossReference)cRelationshipAssignment_4.eContents().get(0);
		private final RuleCall cRelationshipRelationshipIDTerminalRuleCall_4_0_1 = (RuleCall)cRelationshipRelationshipCrossReference_4_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Assignment cColumnsAssignment_6_0 = (Assignment)cGroup_6.eContents().get(0);
		private final RuleCall cColumnsColumnParserRuleCall_6_0_0 = (RuleCall)cColumnsAssignment_6_0.eContents().get(0);
		private final Group cGroup_6_1 = (Group)cGroup_6.eContents().get(1);
		private final Keyword cCommaKeyword_6_1_0 = (Keyword)cGroup_6_1.eContents().get(0);
		private final Assignment cColumnsAssignment_6_1_1 = (Assignment)cGroup_6_1.eContents().get(1);
		private final RuleCall cColumnsColumnParserRuleCall_6_1_1_0 = (RuleCall)cColumnsAssignment_6_1_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Table:
		//	"table" elementID=ID label=STRING "handles" relationship=[Relationship] "{" (columns+=Column ("," columns+=Column)*)?
		//	"}";
		public ParserRule getRule() { return rule; }

		//"table" elementID=ID label=STRING "handles" relationship=[Relationship] "{" (columns+=Column ("," columns+=Column)*)?
		//"}"
		public Group getGroup() { return cGroup; }

		//"table"
		public Keyword getTableKeyword_0() { return cTableKeyword_0; }

		//elementID=ID
		public Assignment getElementIDAssignment_1() { return cElementIDAssignment_1; }

		//ID
		public RuleCall getElementIDIDTerminalRuleCall_1_0() { return cElementIDIDTerminalRuleCall_1_0; }

		//label=STRING
		public Assignment getLabelAssignment_2() { return cLabelAssignment_2; }

		//STRING
		public RuleCall getLabelSTRINGTerminalRuleCall_2_0() { return cLabelSTRINGTerminalRuleCall_2_0; }

		//"handles"
		public Keyword getHandlesKeyword_3() { return cHandlesKeyword_3; }

		//relationship=[Relationship]
		public Assignment getRelationshipAssignment_4() { return cRelationshipAssignment_4; }

		//[Relationship]
		public CrossReference getRelationshipRelationshipCrossReference_4_0() { return cRelationshipRelationshipCrossReference_4_0; }

		//ID
		public RuleCall getRelationshipRelationshipIDTerminalRuleCall_4_0_1() { return cRelationshipRelationshipIDTerminalRuleCall_4_0_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }

		//(columns+=Column ("," columns+=Column)*)?
		public Group getGroup_6() { return cGroup_6; }

		//columns+=Column
		public Assignment getColumnsAssignment_6_0() { return cColumnsAssignment_6_0; }

		//Column
		public RuleCall getColumnsColumnParserRuleCall_6_0_0() { return cColumnsColumnParserRuleCall_6_0_0; }

		//("," columns+=Column)*
		public Group getGroup_6_1() { return cGroup_6_1; }

		//","
		public Keyword getCommaKeyword_6_1_0() { return cCommaKeyword_6_1_0; }

		//columns+=Column
		public Assignment getColumnsAssignment_6_1_1() { return cColumnsAssignment_6_1_1; }

		//Column
		public RuleCall getColumnsColumnParserRuleCall_6_1_1_0() { return cColumnsColumnParserRuleCall_6_1_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class ColumnElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Column");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cColumnKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cElementIDAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cElementIDIDTerminalRuleCall_1_0 = (RuleCall)cElementIDAssignment_1.eContents().get(0);
		private final Assignment cLabelAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLabelSTRINGTerminalRuleCall_2_0 = (RuleCall)cLabelAssignment_2.eContents().get(0);
		private final Keyword cHandlesKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cAttributeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cAttributeAttributeCrossReference_4_0 = (CrossReference)cAttributeAssignment_4.eContents().get(0);
		private final RuleCall cAttributeAttributeIDTerminalRuleCall_4_0_1 = (RuleCall)cAttributeAttributeCrossReference_4_0.eContents().get(1);
		
		//Column:
		//	"column" elementID=ID label=STRING "handles" attribute=[Attribute];
		public ParserRule getRule() { return rule; }

		//"column" elementID=ID label=STRING "handles" attribute=[Attribute]
		public Group getGroup() { return cGroup; }

		//"column"
		public Keyword getColumnKeyword_0() { return cColumnKeyword_0; }

		//elementID=ID
		public Assignment getElementIDAssignment_1() { return cElementIDAssignment_1; }

		//ID
		public RuleCall getElementIDIDTerminalRuleCall_1_0() { return cElementIDIDTerminalRuleCall_1_0; }

		//label=STRING
		public Assignment getLabelAssignment_2() { return cLabelAssignment_2; }

		//STRING
		public RuleCall getLabelSTRINGTerminalRuleCall_2_0() { return cLabelSTRINGTerminalRuleCall_2_0; }

		//"handles"
		public Keyword getHandlesKeyword_3() { return cHandlesKeyword_3; }

		//attribute=[Attribute]
		public Assignment getAttributeAssignment_4() { return cAttributeAssignment_4; }

		//[Attribute]
		public CrossReference getAttributeAttributeCrossReference_4_0() { return cAttributeAttributeCrossReference_4_0; }

		//ID
		public RuleCall getAttributeAttributeIDTerminalRuleCall_4_0_1() { return cAttributeAttributeIDTerminalRuleCall_4_0_1; }
	}

	public class ListElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "List");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cListKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cElementIDAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cElementIDIDTerminalRuleCall_1_0 = (RuleCall)cElementIDAssignment_1.eContents().get(0);
		private final Assignment cLabelAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLabelSTRINGTerminalRuleCall_2_0 = (RuleCall)cLabelAssignment_2.eContents().get(0);
		private final Keyword cHandlesKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cRelationshipAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cRelationshipRelationshipCrossReference_4_0 = (CrossReference)cRelationshipAssignment_4.eContents().get(0);
		private final RuleCall cRelationshipRelationshipIDTerminalRuleCall_4_0_1 = (RuleCall)cRelationshipRelationshipCrossReference_4_0.eContents().get(1);
		
		//List:
		//	"list" elementID=ID label=STRING "handles" relationship=[Relationship];
		public ParserRule getRule() { return rule; }

		//"list" elementID=ID label=STRING "handles" relationship=[Relationship]
		public Group getGroup() { return cGroup; }

		//"list"
		public Keyword getListKeyword_0() { return cListKeyword_0; }

		//elementID=ID
		public Assignment getElementIDAssignment_1() { return cElementIDAssignment_1; }

		//ID
		public RuleCall getElementIDIDTerminalRuleCall_1_0() { return cElementIDIDTerminalRuleCall_1_0; }

		//label=STRING
		public Assignment getLabelAssignment_2() { return cLabelAssignment_2; }

		//STRING
		public RuleCall getLabelSTRINGTerminalRuleCall_2_0() { return cLabelSTRINGTerminalRuleCall_2_0; }

		//"handles"
		public Keyword getHandlesKeyword_3() { return cHandlesKeyword_3; }

		//relationship=[Relationship]
		public Assignment getRelationshipAssignment_4() { return cRelationshipAssignment_4; }

		//[Relationship]
		public CrossReference getRelationshipRelationshipCrossReference_4_0() { return cRelationshipRelationshipCrossReference_4_0; }

		//ID
		public RuleCall getRelationshipRelationshipIDTerminalRuleCall_4_0_1() { return cRelationshipRelationshipIDTerminalRuleCall_4_0_1; }
	}

	public class AttributePageElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AttributePageElement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final RuleCall cTextFieldParserRuleCall_0_0 = (RuleCall)cAlternatives_0.eContents().get(0);
		private final RuleCall cTextAreaParserRuleCall_0_1 = (RuleCall)cAlternatives_0.eContents().get(1);
		private final RuleCall cSelectionFieldParserRuleCall_0_2 = (RuleCall)cAlternatives_0.eContents().get(2);
		private final RuleCall cDateSelectionFieldParserRuleCall_0_3 = (RuleCall)cAlternatives_0.eContents().get(3);
		private final RuleCall cTimeSelectionFieldParserRuleCall_0_4 = (RuleCall)cAlternatives_0.eContents().get(4);
		private final Keyword cHandlesKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cAttributeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cAttributeAttributeCrossReference_2_0 = (CrossReference)cAttributeAssignment_2.eContents().get(0);
		private final RuleCall cAttributeAttributeIDTerminalRuleCall_2_0_1 = (RuleCall)cAttributeAttributeCrossReference_2_0.eContents().get(1);
		
		//AttributePageElement:
		//	(TextField | TextArea | SelectionField | DateSelectionField | TimeSelectionField) "handles" attribute=[Attribute];
		public ParserRule getRule() { return rule; }

		//(TextField | TextArea | SelectionField | DateSelectionField | TimeSelectionField) "handles" attribute=[Attribute]
		public Group getGroup() { return cGroup; }

		//TextField | TextArea | SelectionField | DateSelectionField | TimeSelectionField
		public Alternatives getAlternatives_0() { return cAlternatives_0; }

		//TextField
		public RuleCall getTextFieldParserRuleCall_0_0() { return cTextFieldParserRuleCall_0_0; }

		//TextArea
		public RuleCall getTextAreaParserRuleCall_0_1() { return cTextAreaParserRuleCall_0_1; }

		//SelectionField
		public RuleCall getSelectionFieldParserRuleCall_0_2() { return cSelectionFieldParserRuleCall_0_2; }

		//DateSelectionField
		public RuleCall getDateSelectionFieldParserRuleCall_0_3() { return cDateSelectionFieldParserRuleCall_0_3; }

		//TimeSelectionField
		public RuleCall getTimeSelectionFieldParserRuleCall_0_4() { return cTimeSelectionFieldParserRuleCall_0_4; }

		//"handles"
		public Keyword getHandlesKeyword_1() { return cHandlesKeyword_1; }

		//attribute=[Attribute]
		public Assignment getAttributeAssignment_2() { return cAttributeAssignment_2; }

		//[Attribute]
		public CrossReference getAttributeAttributeCrossReference_2_0() { return cAttributeAttributeCrossReference_2_0; }

		//ID
		public RuleCall getAttributeAttributeIDTerminalRuleCall_2_0_1() { return cAttributeAttributeIDTerminalRuleCall_2_0_1; }
	}

	public class TextFieldElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TextField");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTextFieldKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cElementIDAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cElementIDIDTerminalRuleCall_1_0 = (RuleCall)cElementIDAssignment_1.eContents().get(0);
		private final Assignment cLabelAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLabelSTRINGTerminalRuleCall_2_0 = (RuleCall)cLabelAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cFormatKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cFormatAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cFormatSTRINGTerminalRuleCall_3_1_0 = (RuleCall)cFormatAssignment_3_1.eContents().get(0);
		
		//TextField:
		//	"text-field" elementID=ID label=STRING ("format" format=STRING)?;
		public ParserRule getRule() { return rule; }

		//"text-field" elementID=ID label=STRING ("format" format=STRING)?
		public Group getGroup() { return cGroup; }

		//"text-field"
		public Keyword getTextFieldKeyword_0() { return cTextFieldKeyword_0; }

		//elementID=ID
		public Assignment getElementIDAssignment_1() { return cElementIDAssignment_1; }

		//ID
		public RuleCall getElementIDIDTerminalRuleCall_1_0() { return cElementIDIDTerminalRuleCall_1_0; }

		//label=STRING
		public Assignment getLabelAssignment_2() { return cLabelAssignment_2; }

		//STRING
		public RuleCall getLabelSTRINGTerminalRuleCall_2_0() { return cLabelSTRINGTerminalRuleCall_2_0; }

		//("format" format=STRING)?
		public Group getGroup_3() { return cGroup_3; }

		//"format"
		public Keyword getFormatKeyword_3_0() { return cFormatKeyword_3_0; }

		//format=STRING
		public Assignment getFormatAssignment_3_1() { return cFormatAssignment_3_1; }

		//STRING
		public RuleCall getFormatSTRINGTerminalRuleCall_3_1_0() { return cFormatSTRINGTerminalRuleCall_3_1_0; }
	}

	public class TextAreaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TextArea");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTextAreaKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cElementIDAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cElementIDIDTerminalRuleCall_1_0 = (RuleCall)cElementIDAssignment_1.eContents().get(0);
		private final Assignment cLabelAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLabelSTRINGTerminalRuleCall_2_0 = (RuleCall)cLabelAssignment_2.eContents().get(0);
		
		//TextArea:
		//	"text-area" elementID=ID label=STRING;
		public ParserRule getRule() { return rule; }

		//"text-area" elementID=ID label=STRING
		public Group getGroup() { return cGroup; }

		//"text-area"
		public Keyword getTextAreaKeyword_0() { return cTextAreaKeyword_0; }

		//elementID=ID
		public Assignment getElementIDAssignment_1() { return cElementIDAssignment_1; }

		//ID
		public RuleCall getElementIDIDTerminalRuleCall_1_0() { return cElementIDIDTerminalRuleCall_1_0; }

		//label=STRING
		public Assignment getLabelAssignment_2() { return cLabelAssignment_2; }

		//STRING
		public RuleCall getLabelSTRINGTerminalRuleCall_2_0() { return cLabelSTRINGTerminalRuleCall_2_0; }
	}

	public class SelectionFieldElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SelectionField");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSelectionFieldKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cElementIDAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cElementIDIDTerminalRuleCall_1_0 = (RuleCall)cElementIDAssignment_1.eContents().get(0);
		private final Assignment cLabelAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLabelSTRINGTerminalRuleCall_2_0 = (RuleCall)cLabelAssignment_2.eContents().get(0);
		
		//SelectionField:
		//	"selection-field" elementID=ID label=STRING;
		public ParserRule getRule() { return rule; }

		//"selection-field" elementID=ID label=STRING
		public Group getGroup() { return cGroup; }

		//"selection-field"
		public Keyword getSelectionFieldKeyword_0() { return cSelectionFieldKeyword_0; }

		//elementID=ID
		public Assignment getElementIDAssignment_1() { return cElementIDAssignment_1; }

		//ID
		public RuleCall getElementIDIDTerminalRuleCall_1_0() { return cElementIDIDTerminalRuleCall_1_0; }

		//label=STRING
		public Assignment getLabelAssignment_2() { return cLabelAssignment_2; }

		//STRING
		public RuleCall getLabelSTRINGTerminalRuleCall_2_0() { return cLabelSTRINGTerminalRuleCall_2_0; }
	}

	public class DateSelectionFieldElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "DateSelectionField");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDateSelectionFieldKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cElementIDAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cElementIDIDTerminalRuleCall_1_0 = (RuleCall)cElementIDAssignment_1.eContents().get(0);
		private final Assignment cLabelAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLabelSTRINGTerminalRuleCall_2_0 = (RuleCall)cLabelAssignment_2.eContents().get(0);
		
		//DateSelectionField:
		//	"date-selection-field" elementID=ID label=STRING;
		public ParserRule getRule() { return rule; }

		//"date-selection-field" elementID=ID label=STRING
		public Group getGroup() { return cGroup; }

		//"date-selection-field"
		public Keyword getDateSelectionFieldKeyword_0() { return cDateSelectionFieldKeyword_0; }

		//elementID=ID
		public Assignment getElementIDAssignment_1() { return cElementIDAssignment_1; }

		//ID
		public RuleCall getElementIDIDTerminalRuleCall_1_0() { return cElementIDIDTerminalRuleCall_1_0; }

		//label=STRING
		public Assignment getLabelAssignment_2() { return cLabelAssignment_2; }

		//STRING
		public RuleCall getLabelSTRINGTerminalRuleCall_2_0() { return cLabelSTRINGTerminalRuleCall_2_0; }
	}

	public class TimeSelectionFieldElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TimeSelectionField");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTimeSelectionFieldKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cElementIDAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cElementIDIDTerminalRuleCall_1_0 = (RuleCall)cElementIDAssignment_1.eContents().get(0);
		private final Assignment cLabelAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLabelSTRINGTerminalRuleCall_2_0 = (RuleCall)cLabelAssignment_2.eContents().get(0);
		
		//TimeSelectionField:
		//	"time-selection-field" elementID=ID label=STRING;
		public ParserRule getRule() { return rule; }

		//"time-selection-field" elementID=ID label=STRING
		public Group getGroup() { return cGroup; }

		//"time-selection-field"
		public Keyword getTimeSelectionFieldKeyword_0() { return cTimeSelectionFieldKeyword_0; }

		//elementID=ID
		public Assignment getElementIDAssignment_1() { return cElementIDAssignment_1; }

		//ID
		public RuleCall getElementIDIDTerminalRuleCall_1_0() { return cElementIDIDTerminalRuleCall_1_0; }

		//label=STRING
		public Assignment getLabelAssignment_2() { return cLabelAssignment_2; }

		//STRING
		public RuleCall getLabelSTRINGTerminalRuleCall_2_0() { return cLabelSTRINGTerminalRuleCall_2_0; }
	}

	public class ConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Condition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWithKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final RuleCall cAttributeValueConditionParserRuleCall_1_0 = (RuleCall)cAlternatives_1.eContents().get(0);
		private final RuleCall cCompositeConditionParserRuleCall_1_1 = (RuleCall)cAlternatives_1.eContents().get(1);
		
		//Condition:
		//	"with" (AttributeValueCondition | CompositeCondition);
		public ParserRule getRule() { return rule; }

		//"with" (AttributeValueCondition | CompositeCondition)
		public Group getGroup() { return cGroup; }

		//"with"
		public Keyword getWithKeyword_0() { return cWithKeyword_0; }

		//AttributeValueCondition | CompositeCondition
		public Alternatives getAlternatives_1() { return cAlternatives_1; }

		//AttributeValueCondition
		public RuleCall getAttributeValueConditionParserRuleCall_1_0() { return cAttributeValueConditionParserRuleCall_1_0; }

		//CompositeCondition
		public RuleCall getCompositeConditionParserRuleCall_1_1() { return cCompositeConditionParserRuleCall_1_1; }
	}

	public class AttributeValueConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AttributeValueCondition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAttributeConditionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cConditionIDAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cConditionIDIDTerminalRuleCall_1_0 = (RuleCall)cConditionIDAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cAttributeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cAttributeAttributeCrossReference_3_0 = (CrossReference)cAttributeAssignment_3.eContents().get(0);
		private final RuleCall cAttributeAttributeIDTerminalRuleCall_3_0_1 = (RuleCall)cAttributeAttributeCrossReference_3_0.eContents().get(1);
		private final Keyword cEqualsSignEqualsSignKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cValueAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cValueSTRINGTerminalRuleCall_5_0 = (RuleCall)cValueAssignment_5.eContents().get(0);
		private final Keyword cQuestionMarkKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cTypeAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cTypeConditionTypeEnumRuleCall_7_0 = (RuleCall)cTypeAssignment_7.eContents().get(0);
		
		//AttributeValueCondition:
		//	"attribute-condition" conditionID=ID ":" attribute=[Attribute] "==" value=STRING "?" type=ConditionType;
		public ParserRule getRule() { return rule; }

		//"attribute-condition" conditionID=ID ":" attribute=[Attribute] "==" value=STRING "?" type=ConditionType
		public Group getGroup() { return cGroup; }

		//"attribute-condition"
		public Keyword getAttributeConditionKeyword_0() { return cAttributeConditionKeyword_0; }

		//conditionID=ID
		public Assignment getConditionIDAssignment_1() { return cConditionIDAssignment_1; }

		//ID
		public RuleCall getConditionIDIDTerminalRuleCall_1_0() { return cConditionIDIDTerminalRuleCall_1_0; }

		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }

		//attribute=[Attribute]
		public Assignment getAttributeAssignment_3() { return cAttributeAssignment_3; }

		//[Attribute]
		public CrossReference getAttributeAttributeCrossReference_3_0() { return cAttributeAttributeCrossReference_3_0; }

		//ID
		public RuleCall getAttributeAttributeIDTerminalRuleCall_3_0_1() { return cAttributeAttributeIDTerminalRuleCall_3_0_1; }

		//"=="
		public Keyword getEqualsSignEqualsSignKeyword_4() { return cEqualsSignEqualsSignKeyword_4; }

		//value=STRING
		public Assignment getValueAssignment_5() { return cValueAssignment_5; }

		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_5_0() { return cValueSTRINGTerminalRuleCall_5_0; }

		//"?"
		public Keyword getQuestionMarkKeyword_6() { return cQuestionMarkKeyword_6; }

		//type=ConditionType
		public Assignment getTypeAssignment_7() { return cTypeAssignment_7; }

		//ConditionType
		public RuleCall getTypeConditionTypeEnumRuleCall_7_0() { return cTypeConditionTypeEnumRuleCall_7_0; }
	}

	public class CompositeConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CompositeCondition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCompositeConditionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cConditionIDAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cConditionIDIDTerminalRuleCall_1_0 = (RuleCall)cConditionIDAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cCompositionTypeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cCompositionTypeCompositeConditionTypeEnumRuleCall_4_0 = (RuleCall)cCompositionTypeAssignment_4.eContents().get(0);
		private final Keyword cQuestionMarkKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cTypeAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cTypeConditionTypeEnumRuleCall_6_0 = (RuleCall)cTypeAssignment_6.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//CompositeCondition:
		//	"composite-condition" conditionID=ID ":" "(" compositionType= // TODO add composedCondition
		//	CompositeConditionType "?" type=ConditionType ")";
		public ParserRule getRule() { return rule; }

		//"composite-condition" conditionID=ID ":" "(" compositionType= // TODO add composedCondition
		//CompositeConditionType "?" type=ConditionType ")"
		public Group getGroup() { return cGroup; }

		//"composite-condition"
		public Keyword getCompositeConditionKeyword_0() { return cCompositeConditionKeyword_0; }

		//conditionID=ID
		public Assignment getConditionIDAssignment_1() { return cConditionIDAssignment_1; }

		//ID
		public RuleCall getConditionIDIDTerminalRuleCall_1_0() { return cConditionIDIDTerminalRuleCall_1_0; }

		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }

		//"("
		public Keyword getLeftParenthesisKeyword_3() { return cLeftParenthesisKeyword_3; }

		//compositionType= // TODO add composedCondition
		//CompositeConditionType
		public Assignment getCompositionTypeAssignment_4() { return cCompositionTypeAssignment_4; }

		//// TODO add composedCondition
		//CompositeConditionType
		public RuleCall getCompositionTypeCompositeConditionTypeEnumRuleCall_4_0() { return cCompositionTypeCompositeConditionTypeEnumRuleCall_4_0; }

		//"?"
		public Keyword getQuestionMarkKeyword_5() { return cQuestionMarkKeyword_5; }

		//type=ConditionType
		public Assignment getTypeAssignment_6() { return cTypeAssignment_6; }

		//ConditionType
		public RuleCall getTypeConditionTypeEnumRuleCall_6_0() { return cTypeConditionTypeEnumRuleCall_6_0; }

		//")"
		public Keyword getRightParenthesisKeyword_7() { return cRightParenthesisKeyword_7; }
	}

	public class ConditionConnectorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ConditionConnector");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cAttributeValueConditionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cCompositeConditionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//ConditionConnector returns Condition:
		//	AttributeValueCondition | CompositeCondition;
		public ParserRule getRule() { return rule; }

		//AttributeValueCondition | CompositeCondition
		public Alternatives getAlternatives() { return cAlternatives; }

		//AttributeValueCondition
		public RuleCall getAttributeValueConditionParserRuleCall_0() { return cAttributeValueConditionParserRuleCall_0; }

		//CompositeCondition
		public RuleCall getCompositeConditionParserRuleCall_1() { return cCompositeConditionParserRuleCall_1; }
	}

	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//	"-"? INT;
		public ParserRule getRule() { return rule; }

		//"-"? INT
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}

	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedName returns ecore::EString:
		//	ID ("." ID)*;
		public ParserRule getRule() { return rule; }

		//ID ("." ID)*
		public Group getGroup() { return cGroup; }

		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }

		//(=> "." ID)*
		public Group getGroup_1() { return cGroup_1; }

		//=> "."
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}
	
	
	public class ConditionTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "ConditionType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cShowEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cShowShowKeyword_0_0 = (Keyword)cShowEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cHideEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cHideHideKeyword_1_0 = (Keyword)cHideEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cDisableEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cDisableDisableKeyword_2_0 = (Keyword)cDisableEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cEnableEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cEnableEnableKeyword_3_0 = (Keyword)cEnableEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cNoneEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cNoneNoneKeyword_4_0 = (Keyword)cNoneEnumLiteralDeclaration_4.eContents().get(0);
		
		//enum ConditionType:
		//	Show | Hide | Disable | Enable | None;
		public EnumRule getRule() { return rule; }

		//Show | Hide | Disable | Enable | None
		public Alternatives getAlternatives() { return cAlternatives; }

		//Show
		public EnumLiteralDeclaration getShowEnumLiteralDeclaration_0() { return cShowEnumLiteralDeclaration_0; }

		//"Show"
		public Keyword getShowShowKeyword_0_0() { return cShowShowKeyword_0_0; }

		//Hide
		public EnumLiteralDeclaration getHideEnumLiteralDeclaration_1() { return cHideEnumLiteralDeclaration_1; }

		//"Hide"
		public Keyword getHideHideKeyword_1_0() { return cHideHideKeyword_1_0; }

		//Disable
		public EnumLiteralDeclaration getDisableEnumLiteralDeclaration_2() { return cDisableEnumLiteralDeclaration_2; }

		//"Disable"
		public Keyword getDisableDisableKeyword_2_0() { return cDisableDisableKeyword_2_0; }

		//Enable
		public EnumLiteralDeclaration getEnableEnumLiteralDeclaration_3() { return cEnableEnumLiteralDeclaration_3; }

		//"Enable"
		public Keyword getEnableEnableKeyword_3_0() { return cEnableEnableKeyword_3_0; }

		//None
		public EnumLiteralDeclaration getNoneEnumLiteralDeclaration_4() { return cNoneEnumLiteralDeclaration_4; }

		//"None"
		public Keyword getNoneNoneKeyword_4_0() { return cNoneNoneKeyword_4_0; }
	}

	public class CompositeConditionTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "CompositeConditionType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cOrEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cOrOrKeyword_0_0 = (Keyword)cOrEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cAndEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cAndAndKeyword_1_0 = (Keyword)cAndEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum CompositeConditionType:
		//	Or | And;
		public EnumRule getRule() { return rule; }

		//Or | And
		public Alternatives getAlternatives() { return cAlternatives; }

		//Or
		public EnumLiteralDeclaration getOrEnumLiteralDeclaration_0() { return cOrEnumLiteralDeclaration_0; }

		//"Or"
		public Keyword getOrOrKeyword_0_0() { return cOrOrKeyword_0_0; }

		//And
		public EnumLiteralDeclaration getAndEnumLiteralDeclaration_1() { return cAndEnumLiteralDeclaration_1; }

		//"And"
		public Keyword getAndAndKeyword_1_0() { return cAndAndKeyword_1_0; }
	}
	
	private final FormModelElements pFormModel;
	private final FormElements pForm;
	private final PageElements pPage;
	private final PageElementElements pPageElement;
	private final RelationshipPageElementElements pRelationshipPageElement;
	private final TableElements pTable;
	private final ColumnElements pColumn;
	private final ListElements pList;
	private final AttributePageElementElements pAttributePageElement;
	private final TextFieldElements pTextField;
	private final TextAreaElements pTextArea;
	private final SelectionFieldElements pSelectionField;
	private final DateSelectionFieldElements pDateSelectionField;
	private final TimeSelectionFieldElements pTimeSelectionField;
	private final ConditionElements pCondition;
	private final AttributeValueConditionElements pAttributeValueCondition;
	private final CompositeConditionElements pCompositeCondition;
	private final ConditionConnectorElements pConditionConnector;
	private final ConditionTypeElements unknownRuleConditionType;
	private final CompositeConditionTypeElements unknownRuleCompositeConditionType;
	private final EIntElements pEInt;
	private final QualifiedNameElements pQualifiedName;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public FormGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pFormModel = new FormModelElements();
		this.pForm = new FormElements();
		this.pPage = new PageElements();
		this.pPageElement = new PageElementElements();
		this.pRelationshipPageElement = new RelationshipPageElementElements();
		this.pTable = new TableElements();
		this.pColumn = new ColumnElements();
		this.pList = new ListElements();
		this.pAttributePageElement = new AttributePageElementElements();
		this.pTextField = new TextFieldElements();
		this.pTextArea = new TextAreaElements();
		this.pSelectionField = new SelectionFieldElements();
		this.pDateSelectionField = new DateSelectionFieldElements();
		this.pTimeSelectionField = new TimeSelectionFieldElements();
		this.pCondition = new ConditionElements();
		this.pAttributeValueCondition = new AttributeValueConditionElements();
		this.pCompositeCondition = new CompositeConditionElements();
		this.pConditionConnector = new ConditionConnectorElements();
		this.unknownRuleConditionType = new ConditionTypeElements();
		this.unknownRuleCompositeConditionType = new CompositeConditionTypeElements();
		this.pEInt = new EIntElements();
		this.pQualifiedName = new QualifiedNameElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("at.ac.tuwien.big.forms.form.Form".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//// implement your grammar here, starting with the root element: FormModel
	//FormModel:
	//	forms+=Form*;
	public FormModelElements getFormModelAccess() {
		return pFormModel;
	}
	
	public ParserRule getFormModelRule() {
		return getFormModelAccess().getRule();
	}

	//Form:
	//	welcomeForm?="welcome"? "form" name=ID title=STRING "handles" entity=[Entity] "{" pages+=Page* "}";
	public FormElements getFormAccess() {
		return pForm;
	}
	
	public ParserRule getFormRule() {
		return getFormAccess().getRule();
	}

	//Page:
	//	"page" title=STRING "{" (pageElements+=PageElement ("," pageElements+=PageElement)*)? condition=Condition? "}";
	public PageElements getPageAccess() {
		return pPage;
	}
	
	public ParserRule getPageRule() {
		return getPageAccess().getRule();
	}

	//PageElement:
	//	(RelationshipPageElement | AttributePageElement) condition=Condition?;
	public PageElementElements getPageElementAccess() {
		return pPageElement;
	}
	
	public ParserRule getPageElementRule() {
		return getPageElementAccess().getRule();
	}

	//RelationshipPageElement:
	//	(List | Table) "edits" editingForm=[Form];
	public RelationshipPageElementElements getRelationshipPageElementAccess() {
		return pRelationshipPageElement;
	}
	
	public ParserRule getRelationshipPageElementRule() {
		return getRelationshipPageElementAccess().getRule();
	}

	//Table:
	//	"table" elementID=ID label=STRING "handles" relationship=[Relationship] "{" (columns+=Column ("," columns+=Column)*)?
	//	"}";
	public TableElements getTableAccess() {
		return pTable;
	}
	
	public ParserRule getTableRule() {
		return getTableAccess().getRule();
	}

	//Column:
	//	"column" elementID=ID label=STRING "handles" attribute=[Attribute];
	public ColumnElements getColumnAccess() {
		return pColumn;
	}
	
	public ParserRule getColumnRule() {
		return getColumnAccess().getRule();
	}

	//List:
	//	"list" elementID=ID label=STRING "handles" relationship=[Relationship];
	public ListElements getListAccess() {
		return pList;
	}
	
	public ParserRule getListRule() {
		return getListAccess().getRule();
	}

	//AttributePageElement:
	//	(TextField | TextArea | SelectionField | DateSelectionField | TimeSelectionField) "handles" attribute=[Attribute];
	public AttributePageElementElements getAttributePageElementAccess() {
		return pAttributePageElement;
	}
	
	public ParserRule getAttributePageElementRule() {
		return getAttributePageElementAccess().getRule();
	}

	//TextField:
	//	"text-field" elementID=ID label=STRING ("format" format=STRING)?;
	public TextFieldElements getTextFieldAccess() {
		return pTextField;
	}
	
	public ParserRule getTextFieldRule() {
		return getTextFieldAccess().getRule();
	}

	//TextArea:
	//	"text-area" elementID=ID label=STRING;
	public TextAreaElements getTextAreaAccess() {
		return pTextArea;
	}
	
	public ParserRule getTextAreaRule() {
		return getTextAreaAccess().getRule();
	}

	//SelectionField:
	//	"selection-field" elementID=ID label=STRING;
	public SelectionFieldElements getSelectionFieldAccess() {
		return pSelectionField;
	}
	
	public ParserRule getSelectionFieldRule() {
		return getSelectionFieldAccess().getRule();
	}

	//DateSelectionField:
	//	"date-selection-field" elementID=ID label=STRING;
	public DateSelectionFieldElements getDateSelectionFieldAccess() {
		return pDateSelectionField;
	}
	
	public ParserRule getDateSelectionFieldRule() {
		return getDateSelectionFieldAccess().getRule();
	}

	//TimeSelectionField:
	//	"time-selection-field" elementID=ID label=STRING;
	public TimeSelectionFieldElements getTimeSelectionFieldAccess() {
		return pTimeSelectionField;
	}
	
	public ParserRule getTimeSelectionFieldRule() {
		return getTimeSelectionFieldAccess().getRule();
	}

	//Condition:
	//	"with" (AttributeValueCondition | CompositeCondition);
	public ConditionElements getConditionAccess() {
		return pCondition;
	}
	
	public ParserRule getConditionRule() {
		return getConditionAccess().getRule();
	}

	//AttributeValueCondition:
	//	"attribute-condition" conditionID=ID ":" attribute=[Attribute] "==" value=STRING "?" type=ConditionType;
	public AttributeValueConditionElements getAttributeValueConditionAccess() {
		return pAttributeValueCondition;
	}
	
	public ParserRule getAttributeValueConditionRule() {
		return getAttributeValueConditionAccess().getRule();
	}

	//CompositeCondition:
	//	"composite-condition" conditionID=ID ":" "(" compositionType= // TODO add composedCondition
	//	CompositeConditionType "?" type=ConditionType ")";
	public CompositeConditionElements getCompositeConditionAccess() {
		return pCompositeCondition;
	}
	
	public ParserRule getCompositeConditionRule() {
		return getCompositeConditionAccess().getRule();
	}

	//ConditionConnector returns Condition:
	//	AttributeValueCondition | CompositeCondition;
	public ConditionConnectorElements getConditionConnectorAccess() {
		return pConditionConnector;
	}
	
	public ParserRule getConditionConnectorRule() {
		return getConditionConnectorAccess().getRule();
	}

	//enum ConditionType:
	//	Show | Hide | Disable | Enable | None;
	public ConditionTypeElements getConditionTypeAccess() {
		return unknownRuleConditionType;
	}
	
	public EnumRule getConditionTypeRule() {
		return getConditionTypeAccess().getRule();
	}

	//enum CompositeConditionType:
	//	Or | And;
	public CompositeConditionTypeElements getCompositeConditionTypeAccess() {
		return unknownRuleCompositeConditionType;
	}
	
	public EnumRule getCompositeConditionTypeRule() {
		return getCompositeConditionTypeAccess().getRule();
	}

	//EInt returns ecore::EInt:
	//	"-"? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}

	//QualifiedName returns ecore::EString:
	//	ID ("." ID)*;
	public QualifiedNameElements getQualifiedNameAccess() {
		return pQualifiedName;
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
